#.travis.yml

language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli@latest
  - npm install

script:
  - ng lint
  - ng test --browsers PhantomJS --watch=false

deploy:
  provider: firebase
  token:
    secure: aMFVvCoQft3KPkUdlhfnYFpw5JYBT38BILwFrVLIUYFcHamqh9y/YF4SgIUrISZ977LN1xIuroiKCsG1TVyR5ezd7J+yO1o9RTwj6DLoZP63Jq9gDW7IVlkqvTuvVM3lqwjhsuWbWMY63lG0qHiI+FrU0a0/vozzjqZOmduchZxf5IaW2v+lJJTbXSWKmAxHj3dYwuKGkS6zVNBDNPT/5nKVfX+LtkACboMooshV4ID/Vx8qRmSsEQvdhuh1o3tpC1vmi6eNkoN9L+XQdIrUbusmtAr46JW1pH8culdKcFQSEUzWi1I7E20tXyZMZPqNgIEtT+8oQY0TlNSn2DaQR9cL3C61ACUKIhk+zaHb9vCK+uQuAgVTm/ddO83xHHIRtr8BJlGAunGKr4sU/vDcrwDlMRUXysNBxViIy3j4TQMZ7twjqalrUyoXTuErPy3CNjgIFuqmiIKEN9O3165FN4gE/jDIOgQp/6846MrSgJyL4AMzGwJVtu9pe2Hp0l26seNhDxEpEWCs0qNRoum003znSRVkP3DPJsFyx4tED7VwfNHRqG5QgNxS1XSTSBxGgLkFlPDLN17jvnGocHZthdnWJxZNuJDSXa1od2QMnhm7yU9ZSSnTikUXlIUexSmXp5EXt8lxXITAQRnPx9J8wxzfutcO3NbXB7sC0wtLa0M=
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
