#.travis.yml

language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli@latest
  - npm install

script:
  - ng lint
  - ng test --browsers PhantomJS --watch=false
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: bBaC9KhjrX/avp0XR0N1X5qm0X8jlJgaczQ978bWYmMyCi8KhRNHqtPSMs/Xf3jOre/2QcbPwm2AF7wraCs7k5ptQLLiBeZoLsdblicmt4tWXEJfLZwkBcXijCkEeDxorzpkt17WyvAqk10nBZ2kDx2ZoVrhJpql9kdm93pnx9+4Ss1hrNZ2LROlOjJOxaQ8uGBar065AaTAP46eV0taIL4nuDw4hbwDrJOr+g5Yg0u5sY18f+tPn2AcRY2NIPb33iAOFU6k2nVDCOcAabGXRnLpqD6tR5/fDSvq7cJhKh2uFokNPtseHbspyw49y8d/oyRCnj1bACJ1AQsmoWA7nwxf/1sQhV3SeHdJUH3utM32rl+E0Wnu9U4zmJtTUGYLiVZvFqwCJB1fPzTEv67BVD8MLzMpTUlpIh3+SknZExCnkcbUXDErx4fivSME6FxmvSDxa4HqbJIpX8ndMtRaZDXX+1cqGBaDiboH6L7GWiJUUvb063SKcQ88va9CNX2OI0OYuNkzoFWZZqYLE8jOd0gLCXbTjq+xTA072UK65djGLOskD5UlvIp6hl3aMTVqk7C+uCzntSRtFDaaPdrW4e25eZOOQ2wk1A3Zh9GcXCLz4V5hSkbHG0LD4bT3MouGdqCj5mudESQ7098P82THsRMynAI3gM2XQynT0X/NT4o=
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
